spring.application.name=gateway
server.port=6010

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# NEW PROPERTIES FOR SPRING BOOT 4.0 / WEBFLUX STARTER
# 1. Turn off the automatic dynamic locator
spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

# 2. Define the explicit route using the new prefix structure
spring.cloud.gateway.server.webflux.routes[0].id=wallet-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://WALLET
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/WALLET/**

#stripping the WALLET segment
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

#spring.cloud.gateway.routes[0].id=wallet
#spring.cloud.gateway.routes[0].uri=lb://wallet
#spring.cloud.gateway.routes[0].predicates[0]=Path=/wallet/**
# First filter drops "/orders"
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=localhost


logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web.reactive.handler.SimpleUrlHandlerMapping=TRACE
logging.level.reactor.netty.http.client.HttpClient=DEBUG

